# Base configuration (development)
version: '3.8'
services:
  app:
    container_name: app-dev
    build: 
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.development
    environment:
      - CHOKIDAR_USEPOLLING=true 