version: '3.8'
services:
  app:
    container_name: app-staging
    build:
      context: .
      dockerfile: Dockerfile
      target: staging
    ports:
      - "3000:3000"
    env_file:
      - .env.staging 